# Generated by Django 3.1.6 on 2021-02-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeauser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'instuctor'), (3, 'admin')], null=True),
        ),
    ]
