# Generated by Django 3.1.6 on 2021-02-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210213_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeauser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'STUDENT'), (2, 'INSTRUCTOR'), (3, 'ADMIN')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_correct_answer', to='core.questionchoice'),
        ),
    ]
