# Generated by Django 3.1.6 on 2021-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210213_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='is_true_choice',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
