# Generated by Django 3.1.6 on 2021-02-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210213_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamaccess',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
