# Generated by Django 3.1.6 on 2021-02-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210214_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredquestion',
            name='date',
        ),
    ]
